Acrs 15 save and exit
UKHomeOffice/acrs pull request #32
Opened 2024-05-17 12:59 UTC by TemitopeAyokuHO

## What? 
[ACRS-15](https://collaboration.homeoffice.gov.uk/jira/browse/ACRS-15) Save and Exit (returning user feature)

## Why? 
The save and exit functionality exists on several pages throughout the form. it helps user and save the current form and return in future to continue 

## How? 
- Added save and exit behaviour functionality to allow user to Save and Exit form when user decides to continue later in 
save-and-exit.js file
- Merged ACRS- 61 and ACRS-35 branch to display and test if they work ok 
- Added html pages to inform user the details has been saved

## Testing?
Tested on my local machine 

## Screenshots (optional)
## Anything Else? (optional)
## Check list

- [ ] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ ] I have written tests (if relevant)
- [ ] I have created a JIRA number for my branch
- [ ] I have created a JIRA number for my commit
- [ ] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
- [ ] Ensure drone builds are green especially tests
- [ ] I will squash the commits before merging

2024-05-17 16:02 UTC, jamiecarterHO requested changes
Just a couple of minor things to update copied from IMA.

Also I think you should add a step in acrs/index.js for information-saved with a save-and-exit behaviour like in IMA: https://github.com/UKHomeOffice/ima/blob/master/apps/ima/behaviours/save-and-exit.js. I know we don't send an email on save and exit but we should do the clear session bit.

2024-05-17 23:01 UTC, TemitopeAyokuHO commented on apps/acrs/translations/src/en/validation.json
> +      "required": "You must select an option"
done

2024-05-17 23:02 UTC, TemitopeAyokuHO commented on apps/acrs/sections/summary-data-sections.js
> +        omitChangeLink: true
Yes i reckon

2024-05-17 23:03 UTC, TemitopeAyokuHO commented on apps/acrs/behaviours/continue-report.js
> +    return res.redirect('/ima/cases');
done

2024-05-17 23:05 UTC, TemitopeAyokuHO commented
> Just a couple of minor things to update copied from IMA.
> 
> Also I think you should add a step in acrs/index.js for information-saved with a save-and-exit behaviour like in IMA: https://github.com/UKHomeOffice/ima/blob/master/apps/ima/behaviours/save-and-exit.js. I know we don't send an email on save and exit but we should do the clear session bit.

I think these 2 steps were added already but should be in other ticket

2024-05-20 09:49 UTC, jamiecarterHO commented on apps/acrs/sections/summary-data-sections.js
> +        omitChangeLink: true
Can update this in the other PR and I'll approve this one

2024-05-20 09:52 UTC, jamiecarterHO approved these changes
Approved assuming the save and exit step and behaviour are added in another PR as suggested.

2024-05-20 11:28 UTC, merged