ACRS-20 : Change external in prod to internal in ingress.yaml
UKHomeOffice/acrs pull request #41
Opened 2024-05-21 23:04 UTC by DivineTaminangHO

## What? 

Changing external ingress for prod env in acrs to internal ingress

## Why? 

This ingress is used for internal communication between pods and services and not from the browser

## How? 
For prod in ingress.yaml, the external ingresses have been changed to internal ingress 
## Testing?
## Screenshots (optional)
## Anything Else? (optional)
## Check list

- [ x] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [ ] I have written tests (if relevant)
- [ x] I have created a JIRA number for my branch
- [ x] I have created a JIRA number for my commit
- [x ] I have followed the chris beams method for my commit https://cbea.ms/git-commit/
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
- [x ] Ensure drone builds are green especially tests
- [x ] I will squash the commits before merging

2024-05-22 11:18 UTC, adityababumallisettiHO commented
@DivineTaminangHO We need to replace External Ingress annotations to Internal Ingress ingress annotations in deploy.sh

2024-05-23 10:52 UTC, TemitopeAyokuHO approved these changes

2024-05-23 10:52 UTC, TemitopeAyokuHO commented
LGTM

2024-05-23 10:59 UTC, jamiecarterHO requested changes
Mostly looking good! Couple of questions...

2024-05-23 10:59 UTC, jamiecarterHO commented on kube/hof-rds-api/ingress.yml
> +      {{ else }}
Space added on end of line here...probably ok but hopefully it won't mess with the yaml

2024-05-23 11:32 UTC, DivineTaminangHO reviewed
changed external ingress to internal

2024-05-23 11:33 UTC, DivineTaminangHO reviewed
removed spaces

2024-05-23 12:16 UTC, jamiecarterHO approved these changes
Thanks for updates, looking good.

2024-05-23 12:22 UTC, merged